// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GRIT.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209110408_UpdateNewsItemNullableFix")]
    partial class UpdateNewsItemNullableFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GRIT.Web.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "halil.akinci@artvin.edu.tr",
                            FullName = "GRIT Yönetici",
                            Password = "$2a$11$uJ0Qr2YYPbDCBK1d26Qt7ewRkw6n9ii333yqeELipP/zdtpfR2tpW"
                        });
                });

            modelBuilder.Entity("GRIT.Web.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorTr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryTr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesTr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryTr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleTr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoEmbed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorEn = "Sigortacı Gazetesi",
                            AuthorTr = "Sigortacı Gazetesi",
                            CategoryEn = "Interview",
                            CategoryTr = "Röportaj",
                            Date = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>Prof. Dr. Halil Akıncı discussed the increasing importance of wildfire risk due to climate change.</p>",
                            DescriptionTr = "<p>Prof. Dr. Halil Akıncı, iklim değişikliği ile artan orman yangını risklerinin önemini anlattı.</p>",
                            ExternalUrl = "https://sigortacigazetesi.com.tr/orman-yangini-riskini-azaltmak-icin-haritalar-ve-modellemeler-hayati-rol-oynuyor/",
                            FeaturesEn = "Wildfire Analysis,Risk Modeling,Scientific Approach",
                            FeaturesTr = "Orman Yangını Analizi,Risk Modelleme,Bilimsel Yaklaşım",
                            Image = "/image/halil_2.jpg",
                            SummaryEn = "Prof. Dr. Halil Akıncı explained the growing need for wildfire susceptibility maps.",
                            SummaryTr = "GRİT’in kurucusu Prof. Dr. Halil Akıncı, orman yangını duyarlılık haritalarına duyulan ihtiyacı anlattı.",
                            TitleEn = "Maps and modeling play a vital role in reducing wildfire risks",
                            TitleTr = "Orman yangını riskini azaltmak için haritalar ve modellemeler hayati rol oynuyor"
                        },
                        new
                        {
                            Id = 2,
                            AuthorEn = "Sigorta Dünyası",
                            AuthorTr = "Sigorta Dünyası",
                            CategoryEn = "Interview",
                            CategoryTr = "Röportaj",
                            Date = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>With new generation mapping technologies, high-risk areas can be identified precisely.</p>",
                            DescriptionTr = "<p>Yeni nesil haritalama teknolojileri sayesinde riskli alanlar nokta atışı tespit edilebiliyor.</p>",
                            ExternalUrl = "https://www.sigortadunyasi.com.tr/2025/09/09/orman-yangini-riskinin-yonetiminde-sigortaciliga-bilimsel-modelleme-katkisi/",
                            FeaturesEn = "10m Resolution,Sector Interest,Damage Management",
                            FeaturesTr = "10m Çözünürlük,Sektörel İlgi,Hasar Yönetimi",
                            Image = "/image/halil_2.jpg",
                            SummaryEn = "Prof. Dr. Halil Akıncı stated that new 10m resolution maps attract strong interest in the sector.",
                            SummaryTr = "Prof. Dr. Halil AKINCI, yeni 10m çözünürlüklü haritaların sektörde ilgi gördüğünü belirtti.",
                            TitleEn = "Wildfire susceptibility maps provide major value for the insurance sector",
                            TitleTr = "Orman yangını duyarlılık haritaları sigorta sektörü için ciddi katkı sağlıyor"
                        },
                        new
                        {
                            Id = 3,
                            AuthorEn = "Sigorta Ekranı",
                            AuthorTr = "Sigorta Ekranı",
                            CategoryEn = "Live Broadcast",
                            CategoryTr = "Canlı Yayın",
                            Date = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>The datasets and algorithms were explained in detail during the live broadcast.</p>",
                            DescriptionTr = "<p>Canlı yayında veri setleri ve algoritmalar detaylandırıldı.</p>",
                            ExternalUrl = "https://www.youtube.com/watch?v=hVF3FMabwl0",
                            FeaturesEn = "Live Broadcast,Technical Analysis,Education",
                            FeaturesTr = "Canlı Yayın,Teknik Analiz,Eğitim",
                            Image = "https://img.youtube.com/vi/hVF3FMabwl0/maxresdefault.jpg",
                            SummaryEn = "Prof. Dr. Halil Akıncı discussed technical details of wildfire susceptibility models.",
                            SummaryTr = "Prof. Dr. Halil AKINCI, orman yangını duyarlılık modellerinin teknik detaylarını anlattı.",
                            TitleEn = "Natural Disasters and Insurance 'ACADEMIC PERSPECTIVE' Wildfires",
                            TitleTr = "Doğal Afetler ve Sigorta “AKADEMİK PERSPEKTİF“ Orman Yangınları",
                            VideoEmbed = "https://www.youtube-nocookie.com/embed/hVF3FMabwl0?autoplay=1"
                        },
                        new
                        {
                            Id = 4,
                            AuthorEn = "Sigortacı Gazetesi",
                            AuthorTr = "Sigortacı Gazetesi",
                            CategoryEn = "Interview",
                            CategoryTr = "Röportaj",
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>Risk maps help prevent potential losses and customer grievances.</p>",
                            DescriptionTr = "<p>Risk haritaları mağduriyetlerin önüne geçiyor.</p>",
                            ExternalUrl = "https://sigortacigazetesi.com.tr/detayli-risk-haritalari-sigortacilik-icin-cok-onemli-hale-geldi/",
                            FeaturesEn = "Pricing,Loss Prevention,Risk Analysis",
                            FeaturesTr = "Fiyatlama,Mağduriyet Önleme,Risk Analizi",
                            Image = "/image/sedat.jpg",
                            SummaryEn = "Prof. Dr. Sedat Doğan highlighted the importance of risk maps in policy pricing.",
                            SummaryTr = "Prof. Dr. Sedat Doğan, poliçe fiyatlamasında risk haritalarının önemini anlattı.",
                            TitleEn = "Detailed risk maps have become crucial for the insurance industry",
                            TitleTr = "Detaylı risk haritaları sigortacılık için çok önemli hale geldi"
                        },
                        new
                        {
                            Id = 5,
                            AuthorEn = "Sigortacı Gazetesi",
                            AuthorTr = "Sigortacı Gazetesi",
                            CategoryEn = "Interview",
                            CategoryTr = "Röportaj",
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>Increasing rainfall continues to raise landslide risks.</p>",
                            DescriptionTr = "<p>Artan yağışlar heyelan riskini artırıyor.</p>",
                            ExternalUrl = "https://sigortacigazetesi.com.tr/detayli-risk-haritalari-sigortacilik-icin-cok-onemli-hale-geldi/",
                            FeaturesEn = "Landslide Risk,Public Awareness,Disaster Management",
                            FeaturesTr = "Heyelan Riski,Vatandaş Bilinci,Afet Yönetimi",
                            Image = "/image/cem.jpg",
                            SummaryEn = "Assoc. Prof. Cem Kılıçoğlu emphasized the importance of landslide insurance.",
                            SummaryTr = "Doç. Dr. Cem Kılıçoğlu, heyelan sigortasının önemini vurguladı.",
                            TitleEn = "Getting insured against landslides is now inevitable!",
                            TitleTr = "Heyelanlara karşı sigorta yaptırmak artık kaçınılmaz!"
                        },
                        new
                        {
                            Id = 6,
                            AuthorEn = "Sigorta Ekranı",
                            AuthorTr = "Sigorta Ekranı",
                            CategoryEn = "Live Broadcast",
                            CategoryTr = "Canlı Yayın",
                            Date = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionEn = "<p>The financial cost of floods increases every year.</p>",
                            DescriptionTr = "<p>Taşkın maliyetleri her yıl artıyor.</p>",
                            ExternalUrl = "https://www.youtube.com/watch?v=YZZq0qqq7tk",
                            FeaturesEn = "Flood Models,Financial Impact,Sector Solution",
                            FeaturesTr = "Taşkın Modelleri,Finansal Etki,Sektörel Çözüm",
                            Image = "https://img.youtube.com/vi/YZZq0qqq7tk/maxresdefault.jpg",
                            SummaryEn = "Prof. Dr. Sedat Doğan explained the financial impacts of flood models.",
                            SummaryTr = "Prof. Dr. Sedat DOĞAN, taşkın modellerinin finansal etkilerini anlattı.",
                            TitleEn = "Why do floods and overflows closely concern the insurance sector?",
                            TitleTr = "Sel ve taşkınlar sigorta sektörünü neden yakından ilgilendiriyor?",
                            VideoEmbed = "https://www.youtube.com/embed/YZZq0qqq7tk?autoplay=1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
